import { ArrowRight, Check, Clock3, RotateCcw, ShoppingBag, Trash2, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { routeById } from '../data/routes.js'
import { applyDecisionOutcome } from '../domain/memoryEngine.js'
import { getDecisions, getMemory, removeDecision, saveDecision, saveMemory, saveWardrobeItem } from '../domain/productStore.js'
import { useI18n } from '../hooks/useI18n.js'
import { track } from '../utils/analytics.js'

const filters = ['all','advised','watching','purchased','passed','kept','returned']
const emptyOutcome = { satisfaction: '4', kept: true, returned: false, wearCount: '0', returnReason: '', note: '' }

export function History() {
  const { language, t } = useI18n()
  const [items, setItems] = useState(getDecisions)
  const [filter, setFilter] = useState('all')
  const [feedbackFor, setFeedbackFor] = useState(null)
  const [outcome, setOutcome] = useState(emptyOutcome)
  const [savedMessage, setSavedMessage] = useState('')
  useEffect(() => { const refresh = () => setItems(getDecisions()); window.addEventListener('styleos:v2-change', refresh); return () => window.removeEventListener('styleos:v2-change', refresh) }, [])
  const filtered = useMemo(() => filter === 'all' ? items : items.filter((item) => item.status === filter), [filter, items])
  const setStatus = (decision, status) => { saveDecision({ ...decision, status }); setItems(getDecisions()); track('decision_status_changed', { id: decision.id, status }) }
  const remove = (id) => { removeDecision(id); setItems(getDecisions()) }
  const openFeedback = (decision) => { setFeedbackFor(decision); setOutcome(decision.outcome || emptyOutcome); setSavedMessage('') }
  const submitOutcome = () => {
    const normalized = { ...outcome, satisfaction: Number(outcome.satisfaction), wearCount: Number(outcome.wearCount), kept: Boolean(outcome.kept), returned: Boolean(outcome.returned) }
    const status = normalized.returned || !normalized.kept ? 'returned' : 'kept'
    const updated = saveDecision({ ...feedbackFor, status, outcome: normalized })
    const memory = applyDecisionOutcome(getMemory(), updated, normalized)
    saveMemory(memory)
    if (status === 'kept') saveWardrobeItem({ name: updated.product.name, category: updated.product.category, color: updated.product.color, fit: updated.product.fit, scenes: updated.product.scenes, wearFrequency: normalized.wearCount >= 4 ? 'weekly' : 'monthly', status: 'active', liked: normalized.satisfaction >= 4, notes: normalized.note, sourceDecisionId: updated.id })
    setItems(getDecisions()); setSavedMessage(t('memoryV2.decisions.updated')); track('decision_outcome_submitted', { id: updated.id, status, satisfaction: normalized.satisfaction })
    setTimeout(() => { setFeedbackFor(null); setSavedMessage('') }, 1100)
  }

  return <main className="mx-auto min-h-[calc(100vh-4.5rem)] max-w-[96rem] px-5 pb-24 pt-8 sm:px-8 sm:pt-12 lg:px-12">
    <header className="grid gap-8 border-b border-white/10 pb-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="signal-label text-acid">05 / DECISION OUTCOMES</p><h1 className="mt-6 max-w-5xl font-display text-5xl leading-[.95] tracking-[-.055em] sm:text-7xl">{t('pages.history.title')}</h1><p className="mt-7 max-w-2xl text-base leading-7 text-stone">{t('pages.history.description')}</p></div><Link to={routeById.purchase.path} className="acid-button h-12 gap-3 px-6 text-[10px] uppercase tracking-[.13em]"><ShoppingBag size={15} />{t('memoryV2.common.buyCheck')}</Link></header>
    <div className="mt-6 flex flex-wrap gap-2">{filters.map((item) => <button key={item} type="button" onClick={() => setFilter(item)} className={`rounded-full border px-4 py-2 text-xs ${filter === item ? 'border-acid bg-acid text-paper' : 'border-white/10 text-stone'}`}>{t(`memoryV2.decisions.filters.${item}`)} · {item === 'all' ? items.length : items.filter((decision) => decision.status === item).length}</button>)}</div>
    {filtered.length ? <section className="mt-6 grid gap-3 lg:grid-cols-2">{filtered.map((decision) => <article key={decision.id} className="soft-panel p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-[8px] uppercase tracking-[.14em] text-acid">{t(`memoryV2.decisions.filters.${decision.status}`)} / {decision.id.slice(-5)}</p><h2 className="mt-3 font-display text-2xl">{decision.product.name}</h2><p className="mt-2 text-xs text-stone">{decision.product.category} · {decision.product.color} · {decision.product.fit} · ¥{decision.product.price}</p></div><div className="text-right"><span className={`font-mono text-[9px] uppercase ${decision.result.verdict === 'buy' ? 'text-acid' : decision.result.verdict === 'skip' ? 'text-danger' : 'text-[#e8bd68]'}`}>{t(`memoryV2.purchase.verdicts.${decision.result.verdict}`)}</span><p className="mt-2 font-display text-3xl">{decision.result.totalScore}</p></div></div><div className="mt-5 flex items-center gap-2 border-y border-white/10 py-3 text-[9px] text-stone"><Clock3 size={12} />{new Intl.DateTimeFormat(language === 'zh' ? 'zh-CN' : 'en', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(decision.createdAt))}<span className="ml-auto">{decision.result.memorySnapshot.recordCount} {t('memoryV2.common.records')}</span></div>
      {decision.status === 'advised' || decision.status === 'watching' ? <div className="mt-5 grid grid-cols-3 gap-2"><Action onClick={() => setStatus(decision, 'purchased')} active label={t('memoryV2.decisions.actions.purchased')} /><Action onClick={() => setStatus(decision, 'passed')} label={t('memoryV2.decisions.actions.passed')} /><Action onClick={() => setStatus(decision, 'watching')} label={t('memoryV2.decisions.actions.watching')} /></div> : null}
      {decision.status === 'purchased' ? <button type="button" onClick={() => openFeedback(decision)} className="acid-button mt-5 h-11 w-full gap-3 text-[9px] uppercase tracking-[.12em]"><RotateCcw size={13} />{t('memoryV2.decisions.feedback')}</button> : null}
      {decision.outcome ? <div className="mt-5 rounded-2xl border border-acid/20 bg-acid/[.04] p-4"><div className="flex justify-between"><span className="signal-label text-acid">REAL OUTCOME</span><span className="text-xs">{decision.outcome.satisfaction} / 5</span></div><p className="mt-3 text-xs leading-6 text-stone">{decision.outcome.returnReason || decision.outcome.note || `${decision.outcome.wearCount} wears recorded`}</p></div> : null}
      <div className="mt-4 flex justify-end"><button type="button" onClick={() => remove(decision.id)} className="flex h-8 w-8 items-center justify-center rounded-full border border-white/10 text-stone hover:text-danger"><Trash2 size={13} /></button></div></article>)}</section> : <section className="soft-panel mt-6 flex min-h-96 flex-col items-center justify-center p-8 text-center"><ShoppingBag size={26} className="text-acid" /><p className="mt-6 max-w-md text-sm leading-7 text-stone">{t('memoryV2.decisions.empty')}</p><Link to={routeById.purchase.path} className="mt-6 inline-flex items-center gap-3 text-[10px] uppercase tracking-[.13em] text-acid">{t('memoryV2.common.buyCheck')}<ArrowRight size={14} /></Link></section>}
    {feedbackFor ? <div className="fixed inset-0 z-50 flex items-end justify-end bg-black/70 backdrop-blur-sm"><aside className="h-full w-full max-w-xl overflow-y-auto border-l border-white/10 bg-paper p-6 sm:p-9"><div className="flex justify-between border-b border-white/10 pb-6"><div><p className="signal-label text-acid">OUTCOME / {feedbackFor.id.slice(-5)}</p><h2 className="mt-4 font-display text-3xl">{t('memoryV2.decisions.feedback')}</h2><p className="mt-2 text-sm text-stone">{feedbackFor.product.name}</p></div><button type="button" onClick={() => setFeedbackFor(null)}><X size={16} /></button></div><div className="mt-7"><span className="signal-label">{t('memoryV2.decisions.satisfaction')}</span><div className="mt-3 grid grid-cols-5 gap-2">{[1,2,3,4,5].map((value) => <button key={value} type="button" onClick={() => setOutcome({ ...outcome, satisfaction: String(value) })} className={`h-12 rounded-2xl border text-sm ${Number(outcome.satisfaction) === value ? 'border-acid bg-acid text-paper' : 'border-white/10'}`}>{value}</button>)}</div></div><div className="mt-6 grid grid-cols-2 gap-2"><Toggle label={t('memoryV2.decisions.kept')} active={outcome.kept && !outcome.returned} onClick={() => setOutcome({ ...outcome, kept: true, returned: false })} /><Toggle label={t('memoryV2.decisions.returned')} active={outcome.returned} onClick={() => setOutcome({ ...outcome, kept: false, returned: true })} /></div><label className="mt-6 block"><span className="signal-label">{t('memoryV2.decisions.wearCount')}</span><input type="number" min="0" value={outcome.wearCount} onChange={(event) => setOutcome({ ...outcome, wearCount: event.target.value })} className="mt-2 h-12 w-full rounded-2xl border border-white/10 bg-white/[.035] px-4 outline-none" /></label><label className="mt-5 block"><span className="signal-label">{t('memoryV2.decisions.returnReason')}</span><textarea value={outcome.returnReason} onChange={(event) => setOutcome({ ...outcome, returnReason: event.target.value })} className="mt-2 min-h-24 w-full rounded-2xl border border-white/10 bg-white/[.035] p-4 text-sm outline-none" /></label><label className="mt-5 block"><span className="signal-label">{t('memoryV2.decisions.note')}</span><textarea value={outcome.note} onChange={(event) => setOutcome({ ...outcome, note: event.target.value })} className="mt-2 min-h-20 w-full rounded-2xl border border-white/10 bg-white/[.035] p-4 text-sm outline-none" /></label><button type="button" onClick={submitOutcome} className="acid-button mt-7 h-12 w-full gap-3 text-[9px] uppercase tracking-[.13em]">{savedMessage ? <Check size={14} /> : null}{savedMessage || t('memoryV2.decisions.submit')}</button></aside></div> : null}
  </main>
}

function Action({ label, onClick, active = false }) { return <button type="button" onClick={onClick} className={`button-copy min-h-11 rounded-2xl border px-2 ${active ? 'border-acid/30 text-acid' : 'border-white/10 text-stone'}`}>{label}</button> }
function Toggle({ label, active, onClick }) { return <button type="button" onClick={onClick} className={`flex min-h-14 items-center justify-between rounded-2xl border px-4 text-sm ${active ? 'border-acid bg-acid/[.08] text-acid' : 'border-white/10 text-stone'}`}>{label}{active ? <Check size={14} /> : null}</button> }
