import { ArrowRight, Brain, Check, Edit3, ShieldCheck, Sparkles, Trash2, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { catalogById } from '../data/styleCatalog.js'
import { routeById } from '../data/routes.js'
import { confirmMemoryRecord, removeMemoryRecord, summarizeMemory } from '../domain/memoryEngine.js'
import { getMemory, saveMemory } from '../domain/productStore.js'
import { useI18n } from '../hooks/useI18n.js'

const domains = ['taste','fit','context','wardrobe','behavior','risk']

function Confidence({ value, t }) {
  const percent = Math.round(value * 100)
  const level = percent >= 75 ? 'high' : percent >= 45 ? 'medium' : 'low'
  return <div><div className="mb-2 flex items-center justify-between text-[10px]"><span className="text-stone">{t('memoryV2.common.confidence')} · {t(`memoryV2.common.${level}`)}</span><span>{percent}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/10"><i className={`block h-full rounded-full ${level === 'high' ? 'bg-acid' : level === 'medium' ? 'bg-[#e8bd68]' : 'bg-stone'}`} style={{ width: `${percent}%` }} /></div></div>
}

export function Report() {
  const { language, t } = useI18n()
  const [memory, setMemory] = useState(getMemory)
  const [activeDomain, setActiveDomain] = useState('taste')
  const [editing, setEditing] = useState(null)
  useEffect(() => { const refresh = () => setMemory(getMemory()); window.addEventListener('styleos:v2-change', refresh); return () => window.removeEventListener('styleos:v2-change', refresh) }, [])
  const summary = useMemo(() => summarizeMemory(memory), [memory])
  const visible = summary.byDomain[activeDomain] || []
  const confirm = (id) => { const next = confirmMemoryRecord(memory, id); saveMemory(next); setMemory(next) }
  const remove = (id) => { const next = removeMemoryRecord(memory, id); saveMemory(next); setMemory(next) }
  const saveEdit = () => { const next = { ...memory, updatedAt: new Date().toISOString(), records: memory.records.map((record) => record.id === editing.id ? { ...record, value: editing.value, label: editing.value, confirmed: true, confidence: Math.min(.99, record.confidence + .12), sources: [...new Set([...record.sources, 'user_edit'])], updatedAt: new Date().toISOString() } : record) }; saveMemory(next); setMemory(next); setEditing(null) }
  const recordLabel = (record) => record.kind === 'styleAffinity' ? (catalogById[record.value]?.name || record.label) : record.label

  return <main className="mx-auto min-h-[calc(100vh-4.5rem)] max-w-[96rem] px-5 pb-24 pt-8 sm:px-8 sm:pt-12 lg:px-12">
    <header className="overflow-hidden rounded-[2rem] border border-white/10 bg-surface"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 px-6 py-4 sm:px-9"><p className="signal-label text-acid">03 / LIVING STYLE MEMORY</p><span className="font-mono text-[8px] uppercase tracking-[.13em] text-stone">MEMORY VERSION / {memory.version}</span></div><div className="system-grid grid lg:grid-cols-[1.1fr_.9fr]"><div className="p-7 sm:p-10 lg:border-r lg:border-white/10 lg:p-14"><div className="flex items-center gap-3 text-acid"><Brain size={16} /><span className="signal-label text-acid">{t('memoryV2.memory.overview')}</span></div><h1 className="mt-8 max-w-4xl font-display text-5xl leading-[.94] tracking-[-.055em] sm:text-7xl">{t('pages.report.title')}</h1><p className="mt-7 max-w-2xl text-sm leading-7 text-stone">{t('memoryV2.memory.explain')}</p></div><div className="grid grid-cols-2 gap-px bg-white/10"><div className="flex flex-col justify-end bg-paper/85 p-6"><span className="signal-label">{t('memoryV2.common.confidence')}</span><strong className="mt-4 font-display text-6xl font-normal text-acid">{summary.confidence}%</strong></div><div className="flex flex-col justify-end bg-paper/85 p-6"><span className="signal-label">MEMORY RECORDS</span><strong className="mt-4 font-display text-6xl font-normal">{summary.recordCount}</strong></div><div className="col-span-2 bg-paper/85 p-6"><span className="signal-label">{t('memoryV2.common.updated')}</span><p className="mt-3 text-sm text-stone">{new Intl.DateTimeFormat(language === 'zh' ? 'zh-CN' : 'en', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(summary.updatedAt))}</p></div></div></div></header>

    <div className="mt-5 grid gap-4 lg:grid-cols-[17rem_1fr]">
      <aside className="soft-panel h-fit p-3 lg:sticky lg:top-24">{domains.map((domain) => { const count = summary.byDomain[domain]?.length || 0; return <button key={domain} type="button" onClick={() => setActiveDomain(domain)} className={`flex min-h-14 w-full items-center justify-between rounded-2xl px-4 text-left text-sm transition-colors ${activeDomain === domain ? 'bg-acid text-paper' : 'text-stone hover:bg-white/[.04] hover:text-ink'}`}><span>{t(`memoryV2.memory.domains.${domain}`)}</span><span className={`font-mono text-[8px] ${activeDomain === domain ? 'text-paper/60' : 'text-stone'}`}>{String(count).padStart(2,'0')}</span></button>})}<Link to={routeById.analysis.path} className="button-copy mt-3 flex min-h-12 items-center justify-between rounded-2xl border border-white/10 px-4 text-stone hover:border-acid/30 hover:text-ink">{t('memoryV2.common.setup')}<ArrowRight size={14} /></Link></aside>
      <section className="soft-panel p-5 sm:p-7"><div className="flex items-end justify-between border-b border-white/10 pb-6"><div><p className="signal-label text-acid">MEMORY DOMAIN / {activeDomain.toUpperCase()}</p><h2 className="mt-4 font-display text-3xl">{t(`memoryV2.memory.domains.${activeDomain}`)}</h2></div><span className="font-mono text-[8px] text-stone">{visible.length} {t('memoryV2.common.records')}</span></div>{visible.length ? <div className="mt-5 grid gap-3 sm:grid-cols-2">{visible.sort((a,b) => b.confidence - a.confidence).map((record) => <article key={record.id} className={`rounded-3xl border p-5 ${record.confirmed ? 'border-acid/25 bg-acid/[.035]' : 'border-white/10 bg-white/[.02]'}`}><div className="flex items-start justify-between gap-4"><div><p className="signal-label">{t(`memoryV2.memory.kinds.${record.kind}`)}</p><h3 className="mt-3 font-display text-2xl leading-tight">{recordLabel(record)}</h3></div>{record.confirmed ? <span className="flex h-8 w-8 items-center justify-center rounded-full bg-acid text-paper" title={t('memoryV2.common.confirmed')}><ShieldCheck size={14} /></span> : null}</div><div className="mt-6"><Confidence value={record.confidence} t={t} /></div><div className="mt-5 grid grid-cols-2 gap-2 text-[9px] text-stone"><span>{t('memoryV2.memory.evidenceCount')} · {record.evidenceCount}</span><span className="text-right">{record.sources.join(' / ')}</span></div><div className="mt-5 flex gap-2 border-t border-white/10 pt-4">{!record.confirmed ? <button type="button" onClick={() => confirm(record.id)} className="flex h-9 flex-1 items-center justify-center gap-2 rounded-full border border-acid/25 text-[9px] uppercase tracking-wider text-acid"><Check size={13} />{t('memoryV2.common.confirm')}</button> : null}<button type="button" onClick={() => setEditing({ id: record.id, value: record.label })} className="flex h-9 w-9 items-center justify-center rounded-full border border-white/10 text-stone hover:text-ink"><Edit3 size={13} /></button><button type="button" onClick={() => remove(record.id)} className="flex h-9 w-9 items-center justify-center rounded-full border border-white/10 text-stone hover:text-danger"><Trash2 size={13} /></button></div></article>)}</div> : <div className="flex min-h-72 flex-col items-center justify-center text-center"><Sparkles size={24} className="text-acid" /><p className="mt-5 text-sm text-stone">{t('memoryV2.memory.noRecords')}</p></div>}</section>
    </div>
    {editing ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-5 backdrop-blur-sm"><div className="w-full max-w-md rounded-3xl border border-white/10 bg-surface p-6"><div className="flex justify-between"><p className="signal-label text-acid">EDIT / MEMORY</p><button type="button" onClick={() => setEditing(null)}><X size={16} /></button></div><input autoFocus value={editing.value} onChange={(event) => setEditing({ ...editing, value: event.target.value })} className="mt-6 h-14 w-full rounded-2xl border border-white/10 bg-paper px-4 text-sm outline-none focus:border-acid/40" /><button type="button" onClick={saveEdit} className="acid-button mt-4 h-11 w-full gap-2"><Check size={13} />{t('memoryV2.common.save')}</button></div></div> : null}
  </main>
}
